services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
        working_dir: /workspace
        command: sleep infinity
        networks:
            - devnet
        depends_on:
            - db
            - s3
            - mail

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: hetudevelop
            POSTGRES_PASSWORD: hetudevelop
            POSTGRES_DB: hetudevelop
        networks:
            - devnet
        volumes:
            - pg_data:/var/lib/postgresql/data

    s3:
        image: minio/minio
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: hetudevelop
            MINIO_ROOT_PASSWORD: hetudevelop
        volumes:
            - minio_data:/data
        networks:
            - devnet
        healthcheck:
            test: 'mc ready local'
            interval: 2s
            timeout: 10s
            retries: 5

    s3_init:
        image: minio/minio
        depends_on:
            - s3
        networks:
            - devnet
        restart: on-failure
        entrypoint: >
            /bin/sh -c "
            sleep 5;
            /usr/bin/mc alias set hetu http://s3:9000 hetudevelop hetudevelop;
            /usr/bin/mc mb hetu/textures --ignore-existing;
            /usr/bin/mc anonymous set download hetu/textures;
            exit 0;
            "

    mail:
        image: axllent/mailpit
        volumes:
            - mailpit_data:/data
        networks:
            - devnet
        environment:
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
    devnet:

volumes:
    pg_data:
    minio_data:
    mailpit_data:
